name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: brew update
      run: brew update
    - name: SDL2
      run: brew install sdl2
    - name: SDL2 image
      run: brew install sdl2_image
    - name: SDL2 ttf
      run: brew install sdl2_ttf
    - name: SDL2 mixer
      run: brew install sdl2_mixer
    - name: Lua 
      run: brew install lua
    - name: make
      run: make
    - name: make check
      run: make check
